apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
  labels:
    app: devops-demo-app
spec:
  type: LoadBalancer
  selector:
    app: devops-demo-app
  ports:
    - port: 80
      targetPort: 80

